server:
  port: 8082
spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:h2:mem:movies
    driver-class-name: org.h2.Driver
  username: penta
  password: bar

feign:
  hystrix:
    enabled: true
